# Generated by Django 5.1.15 on 2026-09-06 07:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadis_app', '0003_remove_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма ежемесячного платежа', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Месячная оплата'),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Полная оплата'), ('monthly', 'Помесячная оплата')], default='monthly', help_text='Полная оплата (весь курс сразу) или помесячная', max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_course_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Общая стоимость всего курса', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость курса'),
        ),
    ]
