# Generated by Django 5.1.15 on 2026-09-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadis_app', '0004_student_monthly_fee_student_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='monthly_fee',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_course_fee',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('debt', 'Долг')], default='active', help_text='Статус оплаты/активности ученика', max_length=20, verbose_name='Статус'),
        ),
    ]
