# Generated by Django 5.1.15 on 2026-09-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadis_app', '0005_remove_student_monthly_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Толук төлөп бүттү'), ('debt', 'Төлөө элек'), ('frozen', 'Тоңдурулган'), ('expelled', 'Чыгарылган')], default='active', help_text='Статус оплаты/активности ученика', max_length=20, verbose_name='Статус'),
        ),
    ]
