# Generated by Django 5.1.15 on 2026-09-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadis_app', '0006_update_student_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', 'Активдүү'), ('completed', 'Аяктады'), ('archived', 'Архивделген')], default='active', help_text='Статус активности группы', max_length=20, verbose_name='Статус группы'),
        ),
    ]
